# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriticalInfrastructure
                                 A QGIS plugin
 Add critical infrastructure
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-30
        copyright            : (C) 2024 by Cristian Melendez
        email                : cristian.melendez@upr.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CriticalInfrastructure class from file CriticalInfrastructure.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .critical_infrastructure import CriticalInfrastructure
    return CriticalInfrastructure(iface)
